# Generated by Django 4.2.2 on 2023-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_spam', models.BooleanField(default=False)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
