# Generated by Django 4.2.2 on 2023-07-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamapp', '0003_rename_phone_number_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone_no',
        ),
    ]
